### PR TITLE
compatibility with node 0.12

### PR DESCRIPTION
**Pull request by hannes**
Made package compatible with node 0.12, see https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/ for details

### CODE REVIEW

**Comment by kintel** [comment]
Will this break 0.10 and 0.8 compatibility?

**Comment by hannesmuehleisen** [comment]
yes.

**Comment by kintel** [comment]
Is there a way of getting Travis CI to test the correct version of this package against the correct version of node? Right now, the tests fail.

**Comment by hannesmuehleisen** [comment]
I think it could be specified in the package dependencies. Will investigate.

**Comment by hannesmuehleisen** [comment]
Thanks for the package in the meantime!

**Pull request closed without merging**
